config_name: yolo11_h23
model_name: yolo
hyperparameters:
  model_weights: yolo11n.pt
  epochs: 5
  imgsz: 640
  batch: 32
  device: "0"
coco_json: ../data/h23/instances_subset.json
split_json: ../data/h23/split_h23_subset.json
images_dir: ../data/h23/images
output_dir: ../outputs
wandb_project: freeman-bird-detection
#resume_experiment: yolo11_h23_20260402_004059
#resume_from: ../outputs/yolo11_h23_20260402_004059/work/runs/yolo11_h23_train/weights/last.pt
