model_name: yolo
experiment_name: yolo11_h23
hyperparameters:
  model_weights: yolo11n.pt
  epochs: 10
  imgsz: 640
  batch: 16
  device: "0"
coco_json: ../data/h23/instances_subset.json
split_json: ../data/h23/split_h23_subset.json
images_dir: ../data/h23/images
output_dir: ../outputs
wandb_project: freeman-bird-detection
#resume_experiment: yolo11_h23_20260402_004059
#resume_from: ../outputs/yolo11_h23_20260402_004059/work/runs/yolo11_h23_train/weights/last.pt
