coco_json: ../data/h23/instances_merged.json
split_json: ../data/h23/split.json
images_dir: ../data/h23/images
output_dir: ../outputs
wandb_project: bird-detection
hyperparameters:
  static:
    model_weights: yolo26n.pt
    epochs: 3
  categorical:
  int:
    imgsz: 640
    batch: 32
  float:
    lr: 0.001
